# Generated by Django 5.2.8 on 2025-11-26 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('ip_device', models.GenericIPAddressField(unique=True)),
                ('hostname', models.CharField(blank=True, default='Device', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('state', models.BooleanField(default=False)),
                ('is_access', models.BooleanField(default=True)),
                ('native', models.PositiveIntegerField(default=1)),
                ('allowed_vlan', models.CharField(blank=True, max_length=200, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_device', to='NetVision_Studio.device')),
            ],
        ),
        migrations.CreateModel(
            name='TopologyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_a', to='NetVision_Studio.device')),
                ('device_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_b', to='NetVision_Studio.device')),
                ('interface_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='int_a', to='NetVision_Studio.interface')),
                ('interface_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='int_b', to='NetVision_Studio.interface')),
            ],
        ),
    ]
